### PR TITLE
Improved comments in generated code

### PR DESCRIPTION
**Pull request by WorldofKerry**

### CODE REVIEW

**Review by Haxrox — CHANGES_REQUESTED** [review]
See https://github.com/WorldofKerry/Python2Verilog/issues/134

**Comment by WorldofKerry** [comment]
> 1. Document your protocol in a README that says these signals are active high

While I should also do that, the generated files should not have to be traced back to their source (i.e. this package's readme) to figure out the protocols for their usage.

> 2. Append _H or _L indicating active-high / active-low ([Append _H or _L for active high/low signals #134](https://github.com/WorldofKerry/Python2Verilog/issues/134))
How is this relevant? Should I be appending `_H` to all the input arguments so that user knows that the arguments must be set the same clock cycle as the start signal?

**Comment by Haxrox** [comment]
> should not have to be traced back to their source
While this is a valid reason, having a comment here will require users to find the module when integrating this module somewhere else

> How is this relevant? Should I be appending _H to all the input arguments so that user knows that the arguments must be set the same clock cycle as the start signal?

Oops, the `_H` should only apply to the "done", "valid" comments. The function parameters comment is ok, but really should be documented somewhere else. 

Side note: when you do implement #9, these comments will have to change based off what the user chooses, which adds additional unnecessary complexity

**Comment by WorldofKerry** [comment]
> > should not have to be traced back to their source
> 
> While this is a valid reason, having a comment here will require users to find the module when integrating this module somewhere else

Since we're on the same page on it being a valid reason, I'm not sure what the alternative location for the protocol documentation would be.

> Side note: when you do implement #9, these comments will have to change based off what the user chooses, which adds additional unnecessary complexity

I don't think allowing the user to configure the module protocol is within the scope of that ticket. Right now, the user **must** have valid inputs and have start high in the same clock cycle to properly initialize the module. It is not a matter of whether or not the start signal is active high/low.

**Review by Haxrox — COMMENTED** [review]
I still feel the comments are superfluous, but maybe it's something that's reconsidered once the documentation is more formalized.

**Review by Haxrox — APPROVED** [review]

**Pull request merged**
